name: Manual
on:
  workflow_dispatch:
    inputs:
      url:
        description: '公众号单片文章网址？'
        required: true
        default: "" 
      xlsx:
        description: 'csv or xlsx?'
        required: true
        default: false
  schedule:
    - cron: "0 13 * * 5"
jobs:
  get_list:
    runs-on: ubuntu-latest
    steps:
       - name: check
         uses: actions/checkout@master
       - name: nodejs
         uses: actions/setup-node@v4
         with:
           node-version: '20'
       - name: envrun
         run: |
           npm install node-fetch node-xlsx fs jsdom js-fire
           node index.js "${{ '' || github.event.inputs.url}}" ${{false || github.event.inputs.xlsx}}
       - name: Commit files
         run: |
          git config --local user.email "goonhope@gmail.com"
          git config --local user.name "goonhope"
          git add -A
          git commit -m "Update `date -d '8 hour' '+%Y/%m/%d %H:%M:%S'`" -a
       - name: Push back
         uses: ad-m/github-push-action@master
         with:
           github_token: ${{secrets.GITHUB_TOKEN }}
           branch: main 
